name: Test Homebrew Formula

on:
  pull_request:
    branches:
      - production
    paths:
      - "Formula/neo.rb"

jobs:
  test-formula:
    name: Test Homebrew Formula Installation
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Neo CLI
        run: brew install tvkcompany/neo/neo

      - name: Test Neo CLI
        run: |
          # Test that neo is installed and working
          neo -v

          # Capture the output for the PR comment
          echo "Neo CLI version: $(neo -v)" >> $GITHUB_STEP_SUMMARY
